#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightBack,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     leftBack,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     beaterBar,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S2_C1_1,    backRightServo,       tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    backLeftServoxvxv,    tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    topServo,             tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    backLeftServo,        tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//all naming is this program are based of positive y being forwards and positive x being right
#include "JoystickDriver.c"

short speedMod = 2;
short straifMod = 2;
short turnMod = 1;
short backMod = 2;
short frontMod = 2;
short zero = 6;
float liftmod = 75;

float high = -11.25*360*4;
float mid = -8*360*4;
float low = -4.5*360*4;

void initializeRobot(){
	nMotorEncoder[lift] = 0;
	servo[topServo] = 235;
	servo[backRightServo] = 50;
	servo[backLeftServo] = 256;
	wait1Msec(500);
	servo[backLeftServo] = 127;
  motor[beaterBar] = 50;
  wait1Msec(1000);
  motor[beaterBar] = 0;
}
void liftPos(float x){
	servo[topServo] = 235;
	if(x == 1){
		x = low;
	}else if(x == 2){
		x = mid;
	}else if(x == 3){
		x = high;
	}else if(x == 0){
		x = 0;
	}
	//remember that x is negative bc lift up is counting down and lift down is counting up probs
	if(nMotorEncoder[lift] >= x){
			motor[lift] = 100;
			while(nMotorEncoder[lift] >= x){}
	}else if(nMotorEncoder[lift] <= x){
   		motor[lift] = -100;
   		while(nMotorEncoder[lift] <= x){}
	}
	motor[lift] = 0;
}
void ySet(short speed){
	speed /= speedMod;
	motor[leftFront] = speed;
	motor[leftBack] = speed;
	motor[rightFront] = speed;
	motor[rightBack] = speed;
}
void xSet(short speed){
	speed /= straifMod;
	motor[leftFront] = -speed/frontMod;
	motor[leftBack] = speed/backMod;
	motor[rightFront] = speed/frontMod;
	motor[rightBack] = -speed/backMod;
}
void turn(short speed){
	speed /= turnMod;
	motor[leftBack] = speed;
	motor[rightBack] = -speed;
}
bool liftCheck(float x){
	if(nMotorEncoder[lift] >= 0 + x && nMotorEncoder[lift] <= -(11.25*360) + x){
		return false;
	}
	return true;
}
task main(){
  initializeRobot();
  // wait for start of tele-op phase
  waitForStart();

  //actual control of the robot


  while (true){
		getJoystickSettings(joystick);
		//code for robot panning controlled by the left joystick
		if(joystick.joy1_y1 > zero){ //forwards
			ySet(joystick.joy1_y1);
		}else if(joystick.joy1_y1 < -zero){ //backwards
			ySet(joystick.joy1_y1);
		}else if(joystick.joy1_x1 < -zero){ //left
			xSet(joystick.joy1_x1);
		}else if(joystick.joy1_x1 > zero){ //right
			xSet(joystick.joy1_x1);
		}else if(joystick.joy1_x2 < -zero){ //left turn
			turn(joystick.joy1_x2);
		}else if(joystick.joy1_x2 > zero){ //right turn
			turn(joystick.joy1_x2);
		}else{
			ySet(0);
		}

		//button actions
		switch(joystick.joy1_Buttons){
			case 0:

				break;
			case 1:
				servo[backRightServo] = 190;
	    	servo[backLeftServo] = 0;
	    	wait1Msec(400);
	    	servo[backLeftServo] = 127;
				break;
			case 2:
				servo[backRightServo] = 50;
				servo[backLeftServo] = 256;
				break;
			case 3:
				break;
			case 4:
				break;
			case 5:
				break;
			case 6:
				break;
			case 7:
				break;
			case 8:
				break;
			default:
				break;
		}

		if(joystick.joy2_TopHat != -1){
    	if(joystick.joy2_TopHat == 0){
				liftPos(2);
				//wait1Msec(400);
    	}else if(joystick.joy2_TopHat == 1){
    	}else if(joystick.joy2_TopHat == 2){
    		liftPos(3);
				//wait1Msec(400);
    	}else if(joystick.joy2_TopHat == 3){
    	}else if(joystick.joy2_TopHat == 4){
				liftPos(0);
				//wait1Msec(400);
    	}else if(joystick.joy2_TopHat == 6){
    		liftPos(1);
				//wait1Msec(400);
      }else if(joystick.joy2_TopHat == 5){
    	}else if(joystick.joy2_TopHat == 7){
    	}
    }

    /*
    	JOYSTICK_2!!!!!!!!!!!!!!
    */
    if(joystick.joy2_Buttons & 0x04){
    	//servo[topServo] = 235;
    	motor[beaterBar] = 50;
    }else if(joystick.joy2_Buttons & 0x08){
    	//servo[topServo] = 100;
    	motor[beaterBar] = 0;
    }else if(joystick.joy2_Buttons & 0x01){
    	//motor[beaterBar] = 50;
    	servo[topServo] = 235;
    }else if(joystick.joy2_Buttons & 0x02){
    	//motor[beaterBar] = 0;
    	servo[topServo] = 100;
    }


    if(joystick.joy2_y1 > zero){ //up
			if(liftCheck(liftmod)){
				motor[lift] = liftmod;
			}
		}else if(joystick.joy2_y1 < -zero){ //down
			if(liftCheck(liftmod)){
				motor[lift] = -liftmod;
			}
		}else{
			motor[lift] = 0;
		}
	}
}
