#pragma config(Sensor, S2,     controller,     sensorNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"




 /*
  *
  * joy1 = the joystick on the left, up is + power down is - power
  *
  */
void motorControlProportional()
{
  int nLeftMotor;
  int nRightMotor;

  nLeftMotor = joystick.joy1_y1;
  nRightMotor  = joystick.joy2_y1;
  if (nLeftMotor < 0)
  {
    // Turn left

    motor[motorB] = nLeftMotor; // use power settings from Y-axis

  }
  else
  {
    // Turn right

    motor[motorB]  = nLeftMotor; // use power settings from Y-axis

  }
 /*
  *
  * joy2 = the joystick on the right, up is + power down is - power
  *
  */
  if (nRightMotor < 0)
  {

    motor[motorC] = nRightMotor; // use power settings from Y-axis

  }
  else
  {

    motor[motorC]  = nRightMotor; // use power settings from Y-axis

  }
}
task main()
  {
  	motorControlProportional();

  }
