#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftFront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightBack,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     leftBack,      tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*
	motor[leftFront] = 75;
	motor[rightFront] = 75;
	motor[leftBack] = 75;
	motor[rightBack] = 75;
	wait10Msec(100);
	motor[leftFront] = 0;
	motor[rightFront] = 0;
	motor[leftBack] = 0;
	motor[rightBack] = 0;

	wait10Msec(100);

	motor[leftFront] = -75;
	motor[rightFront] = -75;
	motor[leftBack] = -75;
	motor[rightBack] = -75;
	wait10Msec(100);
	motor[leftFront] = 0;
	motor[rightFront] = 0;
	motor[leftBack] = 0;
	motor[rightBack] = 0;

	wait10Msec(100);
	*/
	motor[leftFront] = -75;
	motor[rightFront] = 75;
	motor[leftBack] = 75;
	motor[rightBack] = -75;
	wait10Msec(100);
	motor[leftFront] = 0;
	motor[rightFront] = 0;
	motor[leftBack] = 0;
	motor[rightBack] = 0;

	wait10Msec(100)

	motor[leftFront] = 75;
	motor[rightFront] = -75;
	motor[leftBack] = -75;
	motor[rightBack] = 75;
	wait10Msec(100);
	motor[leftFront] = 0;
	motor[rightFront] = 0;
	motor[leftBack] = 0;
	motor[rightBack] = 0;

}
