#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     sonar2,         sensorSONAR)
#pragma config(Sensor, S3,     HTSPB,          sensorI2CCustom9V)
#pragma config(Motor,  motorA,          hopperNXT,     tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     hopper,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     fingers,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// based on PSP-Nx-motor-control.c
// http://www.mindsensors.com/index.php?module=documents&JAS_DocumentManager_op=viewDocument&JAS_Document_id=13

const ubyte Addr = 0x02;
const tSensors SensorPort = S4;        // Connect PSPNX sensorto this port!!
#include "PSP-Nx-lib.h"

int nLeftButton = 0;
int nRightButton = 0;
int nEnterButton = 0;
int nExitButton = 0;

const int DeadZone = 15;

//////////////////////////////////////////////////////////////////////////////
//
//      Display the  Gamepad buttons and joystick status  on Nxt screen
//
/////////////////////////////////////////////////////////////////////////////

task
main ()
{
  int powerLeft, powerRight;
  int d_left_X, d_left_Y;
  int d_right_X, d_right_Y;
  int hopper_up, hopper_down, hopper_score;
  int fingers_up, fingers_down;

	psp currState;

  //
  // Note: program cannot be terminated if we hijack the 'exit' button. So there has to be an escape sequence
  //       that will return buttons to system control! We'll use a triple click
  //
  nNxtExitClicks = 3;                // Triple clicking EXIT button will terminate program
  //
  nI2CBytesReady[SensorPort] = 0;

  //SensorType[SensorPort] = sensorI2CCustom9V;        // or perhaps use 'Lowspeed_9V_Custom0'??
  SensorType[SensorPort] = sensorI2CMuxController;
  wait10Msec (100);

  nxtDisplayTextLine (0, "mindsensors.com");
  nxtDisplayTextLine (1, "PSP-NX");

  while ( true )
    {
      wait1Msec (5);

      PSP_ReadButtonState(SensorPort, Addr, currState);

      // joysticks
      d_left_X = (int)currState.l_j_x;
      d_left_Y = (int)currState.l_j_y;
      d_right_X = (int)currState.r_j_x;
      d_right_Y = (int)currState.r_j_y;

      // left button pad
      hopper_down = !(bool)currState.d;
      hopper_up = !(bool)currState.c || !(bool)currState.a;
      hopper_score = !(bool)currState.b;

      // right button pad
      fingers_up = !(bool)currState.triang;
      fingers_down = !(bool)currState.cross;

      /*
      * Determine power for each motor.
       * in doing so, take the Y component of left joystick
       * and X component of right joystick
      */
	    powerLeft = abs(d_left_Y) > DeadZone ? d_left_Y : 0;
	    powerRight = abs(d_right_Y) > DeadZone ? d_right_Y : 0;

		  motor[left] = powerLeft;
		  motor[right] = powerRight;

		  nxtDisplayTextLine(1,"Left: %d", powerLeft);
		  nxtDisplayTextLine(2,"Right: %d", powerRight);

		  // determine where to position hopper
		  if (hopper_down) {
        nxtDisplayTextLine(3,"Hopper down");
      } else if (hopper_up) {
        nxtDisplayTextLine(3,"Hopper up");
      } else if (hopper_score) {
        nxtDisplayTextLine(3,"Hopper score");
      } else {
        // default is up
        nxtDisplayTextLine(3,"Hopper DEFAULT");
      }

		  // determine where to position fingers
		  if (fingers_down) {
        nxtDisplayTextLine(4,"Fingers down");
      } else if (fingers_up) {
        nxtDisplayTextLine(4,"Fingers up");
      } else {
        // default is up
        nxtDisplayTextLine(4,"Fingers DEFAULT");
      }

    }

  wait10Msec (100);

  StopAllTasks ();
}
