#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     HTSPB,          sensorI2CCustom9V)
#pragma config(Sensor, S4,     HTGYRO,         sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "geary-nomux-stuff.c"
/*
task AvoidWalls() {
    while(SensorValue[sonar] > 10)   // While the Sonar Sensor readings are less than the specified, 'distance_in_cm':
      { wait1Msec(300); }
    StopMotors();
    PlayTone(1000,200);
    wait1Msec(500);
    StopAllTasks();
}
*/
//////////////////////////////////////////////////////////////////////////////
//
//      MAIN
//
/////////////////////////////////////////////////////////////////////////////


task
main ()
{
  //int powerA, powerC;
  //int d_left_X, d_left_Y;
  //int d_right_X, d_right_Y;

  //bool go_forward, go_back, go_left, go_right, trigger_pressed;

  //float straightHead;

  // InitProtoboardLights();
  // wait1Msec(1000);

  StartTask(getHeading);
  wait1Msec(300);
  //StartTask(AvoidWalls);
  wait1Msec(300);


  float startHeading = currHeading;
  float flipHeading = startHeading + 180;
  const int onewayDistance = 6000;

  nMotorEncoder[right] = 0;
  while (nMotorEncoder[right] < onewayDistance) {
    GoStraightByGyro(startHeading);
	}



  StopAllTasks ();
}
