#pragma config(Sensor, S4,     HTSMUX,              sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: lego-light-SMUX-test1.c 133 2013-03-10 15:15:38Z xander $
 */

/**
 * lego-light.h provides an API for the Lego Light Sensor.  This program
 * demonstrates how to use that API through a SMUX.
 *
 * Changelog:
 * - 0.1: Initial release
 * - 0.2: More comments
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 3.59 AND HIGHER.

 * Xander Soldaat (xander_at_botbench.com)
 * 25 November 2009
 * version 0.2
 */

#include "../drivers-3x/hitechnic-sensormux.h"
#include "../drivers-3x/lego-light.h"

// The sensor is connected to the first port
// of the SMUX which is connected to the NXT port S1.
// To access that sensor, we must use msensor_S1_1.  If the sensor
// were connected to 3rd port of the SMUX connected to the NXT port S4,
// we would use msensor_S4_3

// Give the sensor a nice easy to use name
const tMUXSensor LEGOLS = msensor_S4_4;

task main() {
  // Turn the light on
  LSsetActive(LEGOLS);
  wait1Msec(1000);
  if (LSvalRaw(LEGOLS) > 800) { // multiplexer must be off, give warning!
  	PlaySound(soundDownwardTones);
    }
  wait1Msec(5000); // show light for 5 more seconds
  LSsetInactive(LEGOLS);
}
