#pragma config(Motor,  motorA,          walker,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define WALKERTARGET 2000
#define WALKERTOLERANCE 20
#define WALKERSPEED 20

task main()
{
  nMotorEncoder[walker] = 0;
  while (abs(nMotorEncoder[walker]-WALKERTARGET) > WALKERTOLERANCE) {
  	motor[walker] = WALKERSPEED;
  }

}
