#pragma config(Sensor, S4,     HTSMUX,              sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: hitechnic-eopd-SMUX-test1.c 133 2013-03-10 15:15:38Z xander $
 */

/**
 * HTCS-driver.h provides an API for the HiTechnic EOPD Sensor.  This program
 * demonstrates how to use that API.
 *
 * Changelog:
 * - 0.1: Initial release
 * - 0.2: Now uses HTSMUX driver which has been split from common.h\n
 *        HTSMUX initialisation and scanning functions have been removed\n
 *
 * Credits:
 * - Big thanks to HiTechnic for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 3.59 AND HIGHER.

 * Xander Soldaat (xander_at_botbench.com)
 * 20 February 2011
 * version 0.2
 */

#include "drivers-3x/hitechnic-sensormux.h"
#include "drivers-3x/hitechnic-eopd.h"
#include "drivers-3x/lego-light.h"

// Give the sensor a nice easy to use name
const tMUXSensor HTEOPD = msensor_S4_3;
const tMUXSensor LEGOLS = msensor_S4_4;


task main() {
  int _raw = 0;
  int _processed = 0;

  // Set the sensor to short range
  HTEOPDsetShortRange(HTEOPD);

  while(true) {
      // Read the raw sensor value
      _raw = HTEOPDreadRaw(HTEOPD);
      // read the processed value which is linear with
      // the distance detected.  Use the processed value
      // when you want to determine distance to an object
      _processed = HTEOPDreadProcessed(HTEOPD);
      nxtDisplayClearTextLine(3);
      nxtDisplayClearTextLine(4);
      nxtDisplayTextLine(4, "Proc:  %4d", _processed);
      nxtDisplayTextLine(3, "Raw :  %4d", _raw);
      wait1Msec(50);
      if (_processed > 22) {
      	      LSsetActive(LEGOLS); // turn light on
	            PlaySound(1024, 50);
	            nxtDisplayTextLine(5, "df :  %4d", _raw);
	            while(bSoundActive);
	            LSsetInactive(LEGOLS); // turn light off

	        } // if ball close
} // while true
} // main
