#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     GYRO,           sensorAnalogInactive)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     rightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightBack,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     leftBack,      tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     beaterBar,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S2_C1_1,    backRightServo,       tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    backLeftServo,        tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    topServo,             tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    fghjk,                tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    sdfgbhnm,             tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    sdfghj,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#include "../drivers-3x/hitechnic-sensormux.h"
#include "../drivers-3x/hitechnic-irseeker-v2.h"
#include "../drivers-3x/hitechnic-gyro.h"

//const tMUXSensor IRS1 = msensor_S4_1;
//const tMUXSensor IRS2 = msensor_S4_2;

float currHeading = 0;

// Task to keep track of the current heading using the HT Gyro
task getHeading () {
	float delTime = 0;
	float prevHeading = 0;
	float curRate = 0;

  HTGYROstartCal(GYRO);
  //PlaySound(soundBeepBeep);
  while (true) {
    time10[T1] = 0;
    curRate = HTGYROreadRot(GYRO);
    if (abs(curRate) > 3) {
      prevHeading = currHeading;
      currHeading = prevHeading + curRate * delTime;
      if (currHeading > 360) currHeading -= 360;
      else if (currHeading < 0) currHeading += 360;
    }
    wait1Msec(5);
    delTime = ((float)time1[T1]) / 1000;
    //delTime /= 1000;
  }
}
void xSet(float power){
	motor[rightBack] = power;
	motor[leftBack] = power;
	motor[leftFront] = power;
	motor[rightFront] = power;
}
void forwardInc(float inches, float power){
	nMotorEncoder[rightBack] = 0;
  nMotorEncoder[leftBack] = 0;

  int head = currHeading;
  int ti = 15;

  motor[rightBack] = power;
  motor[leftBack] = power;

  while(nMotorEncoder[rightBack] < (inches/8.37758040957278)*360 || nMotorEncoder[leftBack] < (inches/8.37758040957278)*360){
  	if(head+4 > currHeading){
  		motor[rightBack] = power+ti;
  		motor[rightFront] = power+ti;
  	}else if(head-4 > currHeading){
  		motor[leftBack] = power-ti;
  		motor[leftFront] = power-ti;
  	}else{
  		motor[rightBack] = power;
  		motor[leftBack] = power;
  		motor[leftFront] = power;
  		motor[rightFront] = power;
  	}
  }

}
void turnDeg(float deg, float power){
	float cd = currHeading;
	if(deg > 0){
		motor[leftBack] = power;
  	motor[rightBack] = -power;
	}else{
		motor[leftBack] = -power;
  	motor[rightBack] = power;
	}
	while(cd+deg >= currHeading){
		wait1Msec(5);
	}
	xSet(0);
}

void initializeRobot(){
	StartTask(getHeading);
}
task main(){
	initializeRobot();
	//waitForStart();
	forwardInc(12, -30);
	wait1Msec(10000);
	turnDeg(45, 30);
	wait1Msec(5000);
	forwardInc(58, -30);
	wait1Msec(10000);
	turnDeg(45, 30);
	wait1Msec(5000);
	forwardInc(51, -30);
	wait1Msec(10000);
	servo[backRightServo] = 190;
	servo[backLeftServo] = 0;
	wait1Msec(400);
  servo[backLeftServo] = 127;
  wait1Msec(6000);
  servo[backRightServo] = 50;
	servo[backLeftServo] = 256;
	forwardInc(24, 30);
	wait1Msec(10000);
}
