#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightFront,    tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightBack,     tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     leftBack,      tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_2,     leftFront,     tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S2_C2_1,     beaterBar,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S2_C1_1,    backRightServo,       tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    backLeftServo,        tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    rightServo,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    leftServo,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//all naming is this program are based of positive y being forwards and positive x being right
#include "JoystickDriver.c"

short speedMod = 2;
short straifMod = 2;
short turnMod = 2;
float backMod = 3;
float frontMod = 2;
short zero = 6;
short nudge = 15;

void initializeRobot(){

  return;
}
void ySet(short speed){
	speed /= speedMod;
	motor[leftFront] = speed;
	motor[leftBack] = speed;
	motor[rightFront] = speed;
	motor[rightBack] = speed;
}
void xSet(short speed){
	speed /= straifMod;
	motor[leftFront] = -speed/frontMod;
	motor[leftBack] = speed/backMod;
	motor[rightFront] = speed/frontMod;
	motor[rightBack] = -speed/backMod;
}
void xdiagSet(short speed){
	motor[leftBack] = speed;
	motor[rightFront] = speed;
}
void negxdiagSet(short speed){
	motor[rightBack] = speed;
	motor[leftFront] = speed;
}
void turn(short speed){
	speed /= turnMod;
	//motor[leftFront] = speed;
	motor[leftBack] = speed;
	//motor[rightFront] = -speed;
	motor[rightBack] = -speed;
}
task main(){
  initializeRobot();

  waitForStart();
	while(true){
		getJoystickSettings(joystick);

		//code for controller 1 to move the robot forwards, backwards, straif left, straif right, turn right, and turn left
		if(joystick.joy1_TopHat != -1){
    	if(joystick.joy1_TopHat == 0){
    		ySet(nudge);
    	}else if(joystick.joy1_TopHat == 1){
    		xdiagSet(nudge);
    	}else if(joystick.joy1_TopHat == 2){
    		xSet(nudge*2);
    	}else if(joystick.joy1_TopHat == 3){
    		negxdiagSet(-nudge);
    	}else if(joystick.joy1_TopHat == 4){
    		ySet(-nudge);
    	}else if(joystick.joy1_TopHat == 5){
    		xdiagSet(-nudge);
    	}else if(joystick.joy1_TopHat == 6){
    		xSet(-nudge*2);
      }else if(joystick.joy1_TopHat == 7){
      	xdiagSet(nudge);
    	}
    }else{
			if(joystick.joy1_y1 > zero){ //forwards
				ySet(joystick.joy1_y1);
			}else if(joystick.joy1_y1 < -zero){ //backwards
				ySet(joystick.joy1_y1);
			}else if(joystick.joy1_x1 < -zero){ //left
				xSet(joystick.joy1_x1);
			}else if(joystick.joy1_x1 > zero){ //right
				xSet(joystick.joy1_x1);
			}else if(joystick.joy1_x2 < -zero){ //left turn
				turn(joystick.joy1_x2);
			}else if(joystick.joy1_x2 > zero){ //right turn
				turn(joystick.joy1_x2);
			}else{
				ySet(0);
			}
		}
		//nudge movement for controller 1;



		//button actions for controller 1
		switch(joystick.joy1_Buttons){
			case 1:
				break;
			case 2:
				break;
			case 3:
				break;
			case 4:
				break;
			case 5:
				servo[backRightServo] = 50;
				servo[backLeftServo] = 190;
				break;
			case 6:
				break;
			case 7:
				servo[backRightServo] = 190;
	    	servo[backLeftServo] = 30;
				break;
			case 8:
				break;
			default:
				break;
		}

	}
}
