#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     HTSPB,          sensorI2CCustom9V)
#pragma config(Sensor, S4,     HTGYRO,         sensorAnalogInactive)
#pragma config(Motor,  mtr_S2_C1_1,     left,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     right,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servo2,               tServoStandard)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "geary-mux-stuff.c"

//////////////////////////////////////////////////////////////////////////////
//
//      MAIN
//
/////////////////////////////////////////////////////////////////////////////


task
main ()
{
  // position stalk and init protoboard for lights
  OrientStalkServo();
  RetractLightServo();
  InitProtoboardLights();

  // begin calculating heading
  StartTask(getHeading);
  wait1Msec(500);

  float startHeading = currHeading;
  while (true) {
    PointStraightByGyro(startHeading);
		}

  StopAllTasks ();
}
