#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftFront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightBack,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     leftBack,      tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	//All time in this program is done with 10Msec, 100 = 1 second
	//
	//forwardLeft and forwardRight both can take - to reverse int backwardsLeft and backwardsRight
  //for ward takes a - to go backwards

	//forward
	StartTask(forward(75, 100));
	wait10Msec(200);
	//backward
	StartTask(forward(-75, 100));
	wait10Msec(200);
	//pan right
	StartTask(right(75, 100));
	wait10Msec(200);
	//pan left
	StartTask(left(75, 100));
	wait10Msec(200);
	//diagonal forward right
	StartTask(forwardRight(75, 100));
	wait10Msec(200);
	//diagonal bacwards left
	StartTask(forwardRight(-75, 100));
	wait10Msec(200);
	//diagonal forward left
	StartTask(forwardLeft(75, 100));
	wait10Msec(200);
	//diagonal backwards right
	StartTask(forwardLeft(-75, 100));
	wait10Msec(200);
	//turn to the right tank style
	StartTask(turn(75, 100));
	wait10Msec(200);
	//turn to the left tank style
	StartTask(turn(-75, 100));
	wait10Msec(200);
}



task forward(int p, int d){
	motor[leftFront] = p;
	motor[rightFront] = p;
	motor[leftBack] = p;
	motor[rightBack] = p;
  wait10Msec(d);
  motor[leftFront] = 0;
	motor[rightFront] = 0;
	motor[leftBack] = 0;
	motor[rightBack] = 0;
}
task right(int p, int d){
	motor[leftFront] = -p;
	motor[rightFront] = p;
	motor[leftBack] = p;
	motor[rightBack] = -p;
  wait10Msec(d);
  motor[leftFront] = 0;
	motor[rightFront] = 0;
	motor[leftBack] = 0;
	motor[rightBack] = 0;

}
task left(int p, int d){
	motor[leftFront] = p;
	motor[rightFront] = -p;
	motor[leftBack] = -p;
	motor[rightBack] = p;
  wait10Msec(d);
  motor[leftFront] = 0;
	motor[rightFront] = 0;
	motor[leftBack] = 0;
	motor[rightBack] = 0;

}
task forwardRight(int p, int d){
	motor[rightFront] = p;
	motor[leftBack] = p;
  wait10Msec(d);
	motor[rightFront] = 0;
	motor[leftBack] = 0;

}
task forwardLeft(int p, int d){
	motor[leftFront] = p;
	motor[rightBack] = p;
  wait10Msec(d);
	motor[leftFront] = 0;
	motor[rightBack] = 0;

}
task turn(int p, int d){
	motor[leftFront] = p;
	motor[rightFront] = -p;
	motor[leftBack] = p;
	motor[rightBack] = -p;
  wait10Msec(d);
  motor[leftFront] = 0;
	motor[rightFront] = 0;
	motor[leftBack] = 0;
	motor[rightBack] = 0;
}
